### ISSUE TITLE
makeAssimilatePrototype invokes getters when copying methods

### ISSUE THREAD

**Issue by timnew** [gaearon/react-hot-api#15]
reference to https://github.com/gaearon/react-hot-loader/issues/131

**Comment by FredyC** [comment]
Just what I was looking for, it was really confusing when getter and setter got invoked right away. Hopefully it will get merged soon.

+1

**Comment by benmosher** [comment]
+1. Seeing some weird stuff with autobinding decorators.

**Comment by gaearon** [comment]
This is fixed in [React Proxy](https://github.com/gaearon/react-proxy) which supersedes this project.
I have no intention of fixing React Hot API anymore.
React Hot Loader will migrate to React Proxy soon.
