### ISSUE TITLE
add new beta 0.14 to peerDependencies

### ISSUE THREAD

**Issue by slorber** [gaearon/react-hot-api#18]
As far as I understand, NPM messes up when trying to depend both `0.14.0-beta1` and on libraries that has declared React as a peerDependency. 

For example 

```
    "react": "0.14.0-beta1",
    "react-date-picker": "2.0.15",
```

Does not work well because `react-date-picker` has `peerDependency >= 0.13.0`

I've seen this commit which seems to be your solution to this problem (that I could validate on my computer for react-date-picker), so I simply add 0.14.0-beta1 to the list.
https://github.com/gaearon/react-hot-api/commit/c11de6c89cf2e5908436580d1689c39adb1c7b2b

By the way, isn't there any better solution? Should I contact every lib author to make the change so that I'm able to use that beta? :'(

**Comment by cesarandreu** [comment]
Is there any way to make it to handle all beta versions?

**Comment by slorber** [comment]
@cesarandreu we are currently discussing this here: https://github.com/facebook/react/issues/4542

In the meantine @gaearon I suggest you use 

```
"peerDependencies": {
      "react": ">=0.11.0 || ^0.14.0-alpha"
},
```

It seems to me that `^0.14.0-alpha` will cover all react alpha + betas + rc for the 0.14.0 version. At least I can effectively retrieve the new -beta3 with this as peerDependency
