### ISSUE TITLE
patchProperty clashes with getter-only-properties in component classes

### ISSUE THREAD

**Issue by Meowtimer** [gaearon/react-hot-api#20]
It should probably do some more introspection using Object.getOwnPropertyDescriptor or some such.

**Comment by gaearon** [comment]
Yes. I plan to fix this, but in https://github.com/gaearon/react-hotify project. (Which, unlike this one, is covered with tests.) We'll move to React Hotify as internal engine in future.

**Comment by Meowtimer** [comment]
Ok. Good luck!
