### ISSUE TITLE
peerDependencies break npm install react@0.14.0-beta3 

### ISSUE THREAD

**Issue by chentsulin** [gaearon/react-hot-api#30]
Should we change `0.14.0-beta1` to `0.14.0-beta3`?

```
"peerDependencies": {
    "react": ">=0.11.0 || 0.13.0-beta.1 || 0.13.0-rc1 || 0.13.0-rc2 || 0.14.0-beta1"
 },
```

Also `0.13.0-beta.1 || 0.13.0-rc1 || 0.13.0-rc2` can be safely removed now?

**Comment by gaearon** [comment]
https://github.com/gaearon/react-hot-api/blob/master/package.json#L20

It's ` ^0.14.0-alpha` now. Should include 0.14 betas. Yes, we can remove 0.13 betas but it's done in `0.5.0-alpha` anyway.
