### ISSUE TITLE
ES6 class constructor not hot-updated?

### ISSUE THREAD

**Issue by syranide** [gaearon/react-hot-api#31]
Sorry if this has been answered elsewhere (or if there's a good technical reason), but it seems that constructors in ES6 classes aren't hot-updated like the rest of the class is?

**Comment by gaearon** [comment]
Good point, I'm not sure. Maybe it's not.
(Though technically, even if it was updated—it would only have effect for newly mounted instances, right?)

**Comment by gaearon** [comment]
Oh wait. Are you referring to `0.4.x` or `0.5.0-alpha`? Alpha uses a different engine.

**Comment by syranide** [comment]
> (Though technically, even if it was updated—it would only have effect for newly mounted instances, right?)

Yeah, but I need to reload the page for it to use the new constructor now.

Also, I (kind of) mistakenly opened this in react-hot-api, I'm really using react-hot-loader. It's currently using react-hot-api 0.4.6. I could try react-hot-loader 2 if you think that might solve it?

**Comment by gaearon** [comment]
@syranide 

It might. Check it and let us know. :-)
If it doesn't, please file in [React Proxy](https://github.com/gaearon/react-proxy), that's what RHL2 uses.

**Comment by syranide** [comment]
It actually did! Awesome :+1: 
Thanks for your awesome work with RHL!
