### ISSUE TITLE
Fall back to ReactUpdateQueue on 0.13 components

### ISSUE THREAD

**Issue by luigy** [gaearon/react-hot-api#5]
Thoughts on fallback to `ReactUpdateQueue.enqueueForceUpdate` on react-0.13 components not created using `React.createClass` and that don't extend `React.Component`?
Here is an [example](https://cldup.com/tzloGtZTvD.mp4) using a patched loader and api that uses the fallback

**Comment by gaearon** [comment]
We can do that! Is it needed? I think I had non-React.Component classes updating correctly in 0.13, but maybe I made a mistake while testing.

**Comment by luigy** [comment]
Strange, this is not working for me.  [This](https://github.com/gaearon/react-hot-api/blob/426307049adc2f5107b84737fd7b5117abd97dc2/modules/deepForceUpdate.js#L18-L20]) is where I'm using `ReactUpdateQueue` for my 0.13 components that don't have a `forceUpdate`. Also, I believe it should be skipping autobinding methods for 0.13 components.
I imagine in the future `forceUpdate` being exposed like they have done with `getDOMNode` and
expect `render` to have `props` passed in on 0.14 :raised_hands:

**Comment by gaearon** [comment]
It skips autobinding in the method itself, I believe.

Is your solution backwards-compatible with 0.12? Can you send a PR?

**Comment by gaearon** [comment]
This will be fixed in `react-hot-loader@1.2.0` which will be released soon.

**Comment by gaearon** [comment]
Fixed and released. Can you please verify it works for you?

**Comment by luigy** [comment]
Yes, lgtm  :smile:
